spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/taskmanager
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=aB3xK9pL2mQ7vT5wZ8nR4cF6hJ1sD0yUeG9tN2rM5kP8oI3jH6lF0dS7wA4qZ1x
jwt.expiration=86400000
